name: bank-service-action
description: "Bank Service Action"
runs:
  using: "composite"
  steps:
    - run: mvn clean test -Dgroups="Unit_Test"
      shell: bash


#runs:
#  run_unit_tests:
#    steps:
#      - name: Run unit test
#        run: mvn clean test -Dgroups="Unit_Test"
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v2
#        if: always()
#        with:
#          report_paths: '**/target/surefire-reports/TEST-*.xml'
#
#  run_integration_tests:
#    steps:
#      - name: Run integration test
#        run: mvn clean test -Dgroups="Integration_Test"
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v2
#        if: always()
#        with:
#          report_paths: '**/target/surefire-reports/TEST-*.xml'

