name: store-service-action
description: "Store Service Action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        ls
        cd store-service
        pwd
        mvn clean package test
      shell: bash

