name: mail-service-action
description: "Mail Service Action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        pwd
        ls
        cd mail-service
        pwd
        mvn clean package test
      shell: bash

