name: pdf-service-action
description: "Pdf Service Action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        pwd
        ls
        cd pdf-service
        pwd
        mvn clean package test
      shell: bash

