name: bank-service-action
description: "Bank Service Action"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - run: |
        pwd
        ls
        cd bank-service
        pwd
        mvn clean package test
      shell: bash

